import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import ModeToggle from '@/components/ModeToggle';
import NavigationMenu from '@/components/NavigationMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}

          <div className="fixed bottom-0 mb-4 flex w-full justify-center gap-4">
            <ModeToggle />
            <NavigationMenu />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
